name: e2e
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          pull_request_number=$(jq '.pull_request.number' <"${GITHUB_EVENT_PATH}")
          echo ${pull_request_number}
