name: e2e
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: "/test2"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: setup
        id: hoge
        if: steps.check.outputs.triggered == 'true'
        run: |
          exit 1
      - name: test
        if: success()
        run: |
          echo success
      - name: test
        if: failure()
        run: |
          echo failure
          
