name: e2e
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: "/test"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: khan/pull-request-comment-trigger@master
        id: check2
        with:
          trigger: "/e2e"
          reaction: rocket
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: setup
        id: hoge
        if: steps.check.outputs.triggered == 'true' || steps.check2.outputs.triggered == 'true'
        run: |
          echo "${{ github.event.issue.number }}"
          echo "${{ toJson(github) }}
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.pull_request.url }}
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${{ github.event.pull_request.url }} | jq ".head.ref"
          #echo "##[set-output name=version;]$()"
          
