name: e2e
on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: "number of pullrequest"
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo ${{ github.event.inputs.prNumber }}
