name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      sha:
        description: "sha of head"
        required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: n-iino/check-status-action@main
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          name: test
          status: queued
          conclusion: neutral
          run-title: "run title"
          summary: "summary"
          head-sha: ${{ github.event.inputs.sha }}
