name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: invoke cross browser regression
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: e2e
          token: ${{ secrets.GH_PAT }}
