name: pr
on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: invoke cross browser regression
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: triggered
          token: ${{ secrets.GH_PAT }}
          inputs: '{ "sha": "${{ github.event.pull_request.head.ref }}" }'
          ref: ${{ github.event.pull_request.head.ref }}
