name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: release
        if: github.event.inputs.release == 'true'
        run: |
          echo "hello"

