name: Manually triggered workflow
on:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get pr number
        id: calc
        run: |
          echo "##[set-output name=pr_number;]$(jq '.pull_request.number' <"${GITHUB_EVENT_PATH}")"
      - uses: n-iino/check-status-action@main
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          name: test
          status: queued
          conclusion: neutral
          run-title: "run title"
          summary: "summary"
          head-sha: "${{ steps.calc.outputs.pr_number }}"
